name: Install GTest
description: Install GTest for your platform
author: David Brill (dvd0bvb)
inputs:
  tag:
    description: Tag or branch name. Default is main.
    required: false
    default: main
  build-type:
    description: Build type
    required: false
    default: Release
  dynamic-msvc-runtime:
    description: Link the msvc runtime dynamically (default, MD) or statically (MT)
    required: false
    default: "true"
  with-msan: 
    description: Build gtest with additional instrumentation for msan
    required: false
    default: "false"
runs: 
  using: "composite"
  steps:
    - name: Determine Msan flags
      if: inputs.with-msan == 'true'
      run: |
        pushd ${{ github.action_path }}
        set build_path=${{ github.action_path }}/llvm-project/build
        set flags="-fsanitize=memory -stdlib=libc++ -L$build_path/lib -lc++abi -I$build_path/include -I$build_path/include/c++/v1"
        ./install-gtest.sh ${{ inputs.tag }} ${{ inputs.build-type }} $flags
        popd
      shell: bash

    - name: Install gtest
      if: inputs.with-msan == 'false' && runner.os != 'Windows'
      run: sudo apt update && sudo apt install libgtest-dev
      shell: bash

    - name: Build and install gtest
      if: inputs.with-msan == 'false' && runner.os == 'Windows'
      run: |
        pushd ${{ github.action_path }}
        .\install-gtest.bat ${{ inputs.tag }} ${{ inputs.build-type }} ${{ inputs.dynamic-msvc-runtime }}
        popd
        echo "CMAKE_PREFIX_PATH=C:/Program Files (x86)/googletest-distribution;$CMAKE_PREFIX_PATH" >> $env:GITHUB_ENV
      shell: pwsh