name: Install GTest
description: Install GTest for your platform
author: David Brill (dvd0bvb)
inputs:
  tag:
    description: Tag or branch name. Default is main.
    required: false
    default: main
  build-type:
    description: Build type
    required: false
    default: Release
  dynamic-msvc-runtime:
    description: Link the msvc runtime dynamically (default, MD) or statically (MT)
    required: false
    default: true
outputs:
  gtest-root:
    description: Root of googletest install
    value: ${{ steps.windows-gtest.outputs.gtest-root }}

runs: 
  using: "composite"
  steps:
    - name: Install gtest
      if:  ${{ runner.os != 'Windows' }}
      run: sudo apt update && sudo apt install libgtest-dev libgmock-dev
      shell: bash

    - name: Build and install gtest
      if: ${{ runner.os == 'Windows' }}
      run: |
        pushd ${{ github.action_path }}
        .\install-gtest.bat ${{ inputs.tag }} ${{ inputs.build-type }} ${{ inputs.dynamic-msvc-runtime }}
        popd        
      shell: pwsh

    - id: windows-gtest
      shell: bash
      run: echo "gtest-root=${{ github.action_path }}/googletest/install" >> "$GITHUB_OUTPUT"