name: Install GTest
description: Install GTest for your platform
author: David Brill (dvd0bvb)
inputs:
  tag:
    description: Tag or branch name. Default is main.
    required: false
    default: main
  build-type:
    description: Build type
    required: false
    default: Release
  dynamic-msvc-runtime:
    description: Link the msvc runtime dynamically (default, MD) or statically (MT)
    required: false
    default: true
runs: 
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: build and install gtest
      if: runner.os != 'Windows'
      run: install-gtest.sh ${{ inputs.tag }} ${{ inputs.build-type }}
      shell: bash
    
    - name:
      if: runner.os == 'Windows'
      run: install-gtest.bat ${{ inputs.tag }} ${{ inputs.build-type }} ${{ inputs.shared-msvc-runtime }}
      shell: pwsh