name: Build Project
description: Build a CMake project
author: David Brill (dvd0bvb)
inputs:
  shell-name:
    description: The shell to run commands in
    required: true
  with-msan:
    description: Install libc++ with msan
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Build and Install
      if: inputs.with-msan == 'true'
      working-directory: ${{ github.action_path }}
      shell: ${{ inputs.shell-name }}
      run: ./build-with-msan.sh
    
    - name: Install
      if: inputs.with-msan == 'false'
      shell: ${{ inputs.shell-name }}
      run: sudo apt update && sudo apt install -y libc++-dev libc++abi-dev