name: Install libc++
description: Install libc++ to link with clang
author: David Brill (dvd0bvb)
inputs:
  shell-name:
    description: The shell to run commands in
    required: true
  with-msan:
    description: Install libc++ with msan
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Install
      if: inputs.with-msan == 'true'
      shell: ${{ inputs.shell-name }}
      run: |
        wget $(wget -q -O - https://api.github.com/repos/dvd0bvb/libcxx-with-msan/releases/latest  |  jq -r '.assets[] | select(.name | contains ("deb")) | .browser_download_url')        
        sudo dpkg -i libc++-with-msan-v1.0.0.deb
    
    - name: Install
      if: inputs.with-msan == 'false'
      shell: ${{ inputs.shell-name }}
      run: sudo apt update && sudo apt install -y libc++-dev libc++abi-dev