name: Update the coverage badge
description: Update the code coverage badge
author: David Brill (dvd0bvb)
inputs:
  lcov-file:
    description: The lcov info file
    required: true
outputs:
  line-percent:
    description: The percent of lines which were run
    value: ${{ steps.stats.outputs.lines }}
  function-percent:
    description: The percent of functions which were run
    value: ${{ steps.stats.outputs.functions }}
  branch-percent:
    description: The percent of branches which were run
    value: ${{ steps.stats.outputs.branches }}

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.12.3

    - id: stats
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        pip install -r requirements.txt
        JSON_DATA=$(python3 parse-coverage.py ${{ inputs.lcov-file }})
        echo "lines=$(echo $JSON_DATA | jq '.lines')" >> "$GITHUB_OUTPUT"
        echo "functions=$(echo $JSON_DATA | jq '.functions')" >> "$GITHUB_OUTPUT"
        echo "branches=$(echo $JSON_DATA | jq '.branches')" >> "$GITHUB_OUTPUT"
