name: Get Project Constants
description: Update the code coverage badge
author: David Brill (dvd0bvb)
outputs:
  project-name:
    description: The value of the CMake variable $THIS_PROJECT_NAME
    value: ${{ steps.set-outputs.outputs.project-name }}

  output-type-cmake-flag:
    description: The value of the CMake flag which indicates the build type
    value: ${{ steps.set-output.outputs.output-type-cmake-flag }}

runs:
  using: "composite"  
  steps:
    # Windows does not have PyYAML installed by default
    - if: runner.os == 'Windows'
      uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - if: runner.os == 'Windows'
      shell: bash
      run: pip install PyYAML

    - id: set-outputs
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        yaml() {
          python3 -c "import yaml;print(yaml.safe_load(open('$1'))$2)"
        }

        YAML_FILE=.project-config.yml
        NAME=$(yaml "$YAML_FILE" "['project-name']")
        SHARED=$(yaml "$YAML_FILE" "['build-shared']")
        EXE=$(yaml "$YAML_FILE" "['build-executable']")
        HEADER_ONLY=$(yaml "$YAML_FILE" "['build-header-only']")

        echo "project-name=$NAME" >> "$GITHUB_OUTPUT"

        if [ "$SHARED" = "true" ]; then
          echo "output-type-cmake-flag=-DBRILLIANT_CMAKE_BUILD_SHARED=ON" >>"$GITHUB_OUTPUT"
        elif [ "$EXE" = "true" ]; then
          echo "output-type-cmake-flag=-DBRILLIANT_CMAKE_BUILD_EXECUTABLE=ON" >>"$GITHUB_OUTPUT"
        elif [ "$HEADER_ONLY" = "true" ]; then
          echo "output-type-cmake-flag=-DBRILLIANT_CMAKE_BUILD_HEADER_ONLY=ON" >>"$GITHUB_OUTPUT"
        fi
