name: Update the coverage badge
description: Update the code coverage badge
author: David Brill (dvd0bvb)
inputs:
  shell-name:
    description: The shell to run commands in
    required: true
  lcov-file:
    description: The lcov info file
    required: true
  warning:
    description: Warning threshold
    required: false
    default: 90
  critical:
    description: Critical threshold
    required: false
    default: 85
runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.12.3

    - name: Update coverage badge
      working-directory: ${{ github.action_path }}
      shell: ${{ inputs.shell-name }}
      run: |
        pip install -r requirements.txt
        python ./make-coverage-badge.py ${{ inputs.lcov-file }} coverage.svg --warning ${{ inputs.warning }} --critical ${{ inputs.critical }}
    
    - name: Push coverage badge to github
      shell: ${{ inputs.shell-name }}
      run: |
        git commit coverage.svg -m '[skip ci] updated coverage badge from CI action'
        git push
      
      