name: clang-format Check
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ] 
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
        matrix:
          path:
            - 'src'
            - 'include/project'
            - 'test'
    steps:
    - uses: actions/checkout@v4
    - uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: 18
        check-path: ${{ matrix.path }}