name: cmake-format Check
on: 
  push:
    paths-ignore: 
      - .github/badges/**
      - README.md
  pull_request:
    paths-ignore: 
      - .github/badges/**
      - README.md
      
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@v2
    - uses: puneetmatharu/cmake-format-lint-action@v1.0.4
      with:
        args: --check -c .cmake-format