name: Cppcheck

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - .github/badges/**
      - README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - .github/badges/**
      - README.md

jobs:
  cppcheck:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: cppcheck
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}

    - name: Update badge
      run: |
        COLORS_JSON=./.github/badges/colors.json
        OUT_FILE=./.github/badges/cppcheck.json
        NUM_ERRORS=$(grep -c "error" cppcheck_error.txt)
        
        if [[ $NUM_ERRORS != "0" ]]; then
          COLOR_NAME=critical
          MESSAGE="Errors: $NUM_ERRORS"
        else
          COLOR_NAME=good
          MESSAGE="No Errors"
        fi
        COLOR="$(jq .$COLOR_NAME $COLORS_JSON)"

        jq ".color = $COLOR | .message = \"$MESSAGE\"" $OUT_FILE > json.tmp
        mv json.tmp $OUT_FILE

    - name: Push cppcheck json
      continue-on-error: true
      working-directory: ${{ github.workspace }}
      run: |
        RESULT=$(git diff .github/badges/cppcheck.json)
        if [ ! -z "$RESULT" ]; then
          git commit .github/badges/cppcheck.json -m '[skip ci] updated cppcheck json from CI action'
          git push
        fi