name: Memory Sanitizer

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - .github/badges/**
      - README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - .github/badges/**
      - README.md

jobs:
  memory_sanitizer:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-project
      with: 
        c-compiler: clang
        cpp-compiler: clang++
        build-type: Debug
        use-libcxx: true
        sanitizer: MSAN