name: Thread Sanitizer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  thread_sanitizer:
    runs-on: ubuntu-24.04    
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-project
      with: 
        c-compiler: clang
        cpp-compiler: clang++
        build-type: Debug
        use-libcxx: true
        sanitizer: TSAN