name: Threading

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  thread_sanitizer:
    uses: picanumber/sanitizer_workflows/.github/workflows/tsan.yml@main  
    with: 
        compiler_package: 'g++-13'
        compiler_name: 'g++-13'